Added batch set penalty method
sweatco/sweat-jar pull request #58
Opened 2023-10-25 12:16 UTC by VladasZ

2023-10-26 18:04 UTC, vasyafromrussia requested changes
Small issues

2023-10-26 18:04 UTC, vasyafromrussia commented on contract/src/penalty/api.rs
> +    /// * `jars` - Array containing `AccountId` and `Vec<JarIdView>` for each user and each jar.
-> List of Account IDs and their Jar IDs to which penalty must be applied.

2023-10-26 18:04 UTC, vasyafromrussia commented on contract/src/penalty/api.rs
> +                };
The same check is used in set_penalty for a single Jar. So it's better to extract this to an assertion method

2023-10-26 18:04 UTC, vasyafromrussia commented on contract/src/penalty/api.rs
> +                };
Split it to assertion and applying of penalty, I mean

2023-10-26 21:24 UTC, VladasZ commented on contract/src/penalty/api.rs
> +    /// * `jars` - Array containing `AccountId` and `Vec<JarIdView>` for each user and each jar.
Most of my comments usually sound like a caveman speach =)

2023-10-27 08:50 UTC, georgebancila commented
@vasyafromrussia @VladasZ hey guys 👋🏼 
Can you return `timestamp` in `PenaltyData` too? The timestamp you used when you apply the penalty, [this one](https://github.com/sweatco/sweat-jar/pull/58/files#diff-202944cbf776d1244b148fd2bb03e713332492f16423a30e3fbd545a4aae264bR68). It would help us calculate accurately the interest when showing on FE or on BE push notifications.

2023-10-27 09:22 UTC, VladasZ commented
Done

2023-10-27 13:45 UTC, vasyafromrussia approved these changes

2023-10-27 13:45 UTC, merged